stages:
  - test
  - deploy

variables:
  POSTGRES_DB: todo_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123

services:
  - postgres:latest

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - master
