version: '3'
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "todo_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

